# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "rust:latest"

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - cargo build --release
  cache:
    paths:
      - target/
  artifacts:
    paths:
      - target/release/samotop
      - Cargo.lock

test:
  stage: test
  script:
    - rustc --version && cargo --version
    - cargo test --all --release
  cache:
    paths:
      - target/

publish:
  stage: deploy
  only:
    - master
  except:
    - schedules
  script:
    - cargo publish --token "$CRATES_KEY"
  cache:
    paths:
      - target/