# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "rust:latest"

stages:
  - build
  - test
  - deploy

build-all-features:
  stage: build
  script:
    - rustc --version && cargo --version
    - cargo build --features tls
  cache:
    paths:
      - target/
  artifacts:
    paths:
      - target/release/samotop
      - Cargo.lock
  except:
    - tags

test-no-tls:
  stage: test
  script:
    - cargo test --all
  cache:
    paths:
      - target/
  except:
    - tags

test-with-tls:
  stage: test
  script:
    - cargo test --all --features tls
  cache:
    paths:
      - target/
  except:
    - tags

publish:
  stage: deploy
  only:
    - master
  except:
    - schedules
  script:
    - cargo publish --token "$CRATES_KEY"
  cache:
    paths:
      - target/
  except:
    - tags