[package]
name = "samotop"
version = "0.4.5"
authors = ["jocutajar <tellnoone@robajz.info>"]
build = "src/peg.rs"
exclude = [
    "downloads/*"
]
description = "SMTP server and library built on tokio"
documentation = "https://docs.rs/samotop/"
homepage = "https://gitlab.com/BrightOpen/BackYard/Samotop/"
repository = "https://gitlab.com/BrightOpen/BackYard/Samotop/"
readme = "README.md"
keywords = ["smtp", "tokio", "server", "parser", "PEG"]

# see crates.io/category_slugs
categories = ["email", "asynchronous", "network-programming", "parser-implementations"]

# This is an SPDX 2.1 license expression for this package.  Currently
# crates.io will validate the license provided against a whitelist of
# known license and exception identifiers from the SPDX license list
# 2.4.  Parentheses are not currently supported.
#
# Multiple licenses can be separated with a `/`, although that usage
# is deprecated.  Instead, use a license expression with AND and OR
# operators to get more explicit semantics.
license = "MIT"

[badges]
gitlab = { repository = "BrightOpen/BackYard/Samotop", branch = "develop" }

[dependencies]
log = "0.4"
env_logger = "0.5"
structopt = "0.2"
peg = "0.5"
tokio = "0.1"
tokio-io = "0.1"
tokio-codec = "0.1"
futures = "0.1"
bytes = "0.4"
regex = "1.0"
hostname = "0.1"

[build-dependencies]
peg = { version = "0.5" }