[package]
name = "samotop"
version = "0.1.1"
authors = ["Robert Cutajar <github-commit@robajz.info>"]
build = "src/peg.rs"

[dependencies]
log = "0.4"
env_logger = "0.5.10"
structopt = "0.2"
peg = "0.5.4"
bytes = "0.4"
futures = "0.1"
tokio-io = "0.1"
tokio-core = "0.1"
tokio-proto = "0.1"
tokio-service = "0.1"

[build-dependencies]
peg = { version = "0.5.2" }
